

services:
  postgres:
    image: postgres:latest
    container_name: media_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mediacmn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - media_network

  redis:
    image: redis:latest
    container_name: media_redis
    restart: unless-stopped
    # expose:
    #   - "6379"
    ports:
      - "9001:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redis123
    networks:
      - media_network

volumes:
  postgres_data:
  redis_data:

networks:
  media_network:
    driver: bridge