"""描述变更内容

Revision ID: 6c76c90f8f44
Revises: 
Create Date: 2025-11-25 00:34:56.993699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c76c90f8f44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_external_ids_core_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_source'), table_name='external_ids')
    op.alter_column('file_asset', 'size',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('idx_file_asset_core_id'), table_name='file_asset')
    op.drop_index(op.f('idx_file_asset_full_path'), table_name='file_asset')
    op.drop_index(op.f('idx_file_asset_storage_id'), table_name='file_asset')
    op.drop_index(op.f('idx_file_asset_user_id'), table_name='file_asset')
    op.drop_index(op.f('idx_media_core_kind'), table_name='media_core')
    op.drop_index(op.f('idx_media_core_title'), table_name='media_core')
    op.drop_index(op.f('idx_media_core_user_id'), table_name='media_core')
    op.drop_index(op.f('idx_media_core_year'), table_name='media_core')
    op.drop_index(op.f('idx_scan_job_status'), table_name='scan_job')
    op.drop_index(op.f('idx_scan_job_user_id'), table_name='scan_job')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_scan_job_user_id'), 'scan_job', ['user_id'], unique=False)
    op.create_index(op.f('idx_scan_job_status'), 'scan_job', ['status'], unique=False)
    op.create_index(op.f('idx_media_core_year'), 'media_core', ['year'], unique=False)
    op.create_index(op.f('idx_media_core_user_id'), 'media_core', ['user_id'], unique=False)
    op.create_index(op.f('idx_media_core_title'), 'media_core', ['title'], unique=False)
    op.create_index(op.f('idx_media_core_kind'), 'media_core', ['kind'], unique=False)
    op.create_index(op.f('idx_file_asset_user_id'), 'file_asset', ['user_id'], unique=False)
    op.create_index(op.f('idx_file_asset_storage_id'), 'file_asset', ['storage_id'], unique=False)
    op.create_index(op.f('idx_file_asset_full_path'), 'file_asset', ['full_path'], unique=False)
    op.create_index(op.f('idx_file_asset_core_id'), 'file_asset', ['core_id'], unique=False)
    op.alter_column('file_asset', 'size',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('idx_external_ids_source'), 'external_ids', ['source'], unique=False)
    op.create_index(op.f('idx_external_ids_core_id'), 'external_ids', ['core_id'], unique=False)
    # ### end Alembic commands ###
