"""添加部分字段

Revision ID: aa894e503c38
Revises: 6c76c90f8f44
Create Date: 2025-11-26 00:27:28.067761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'aa894e503c38'
down_revision: Union[str, Sequence[str], None] = '6c76c90f8f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_external_ids_core_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_source'), table_name='external_ids')
    op.drop_index(op.f('idx_file_asset_core_id'), table_name='file_asset')
    op.drop_index(op.f('idx_file_asset_full_path'), table_name='file_asset')
    op.drop_index(op.f('idx_file_asset_storage_id'), table_name='file_asset')
    op.drop_index(op.f('idx_file_asset_user_id'), table_name='file_asset')
    op.drop_index(op.f('idx_media_core_kind'), table_name='media_core')
    op.drop_index(op.f('idx_media_core_title'), table_name='media_core')
    op.drop_index(op.f('idx_media_core_user_id'), table_name='media_core')
    op.drop_index(op.f('idx_media_core_year'), table_name='media_core')
    op.add_column('movie_ext', sa.Column('backdrop_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('movie_ext', sa.Column('imdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('movie_ext', sa.Column('runtime_minutes', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_scan_job_status'), table_name='scan_job')
    op.drop_index(op.f('idx_scan_job_user_id'), table_name='scan_job')
    op.add_column('tv_series_ext', sa.Column('last_aired_date', sa.DateTime(), nullable=True))
    op.add_column('tv_series_ext', sa.Column('episode_run_time', sa.Integer(), nullable=True))
    op.add_column('tv_series_ext', sa.Column('backdrop_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_series_ext', 'backdrop_path')
    op.drop_column('tv_series_ext', 'episode_run_time')
    op.drop_column('tv_series_ext', 'last_aired_date')
    op.create_index(op.f('idx_scan_job_user_id'), 'scan_job', ['user_id'], unique=False)
    op.create_index(op.f('idx_scan_job_status'), 'scan_job', ['status'], unique=False)
    op.drop_column('movie_ext', 'runtime_minutes')
    op.drop_column('movie_ext', 'imdb_id')
    op.drop_column('movie_ext', 'backdrop_path')
    op.create_index(op.f('idx_media_core_year'), 'media_core', ['year'], unique=False)
    op.create_index(op.f('idx_media_core_user_id'), 'media_core', ['user_id'], unique=False)
    op.create_index(op.f('idx_media_core_title'), 'media_core', ['title'], unique=False)
    op.create_index(op.f('idx_media_core_kind'), 'media_core', ['kind'], unique=False)
    op.create_index(op.f('idx_file_asset_user_id'), 'file_asset', ['user_id'], unique=False)
    op.create_index(op.f('idx_file_asset_storage_id'), 'file_asset', ['storage_id'], unique=False)
    op.create_index(op.f('idx_file_asset_full_path'), 'file_asset', ['full_path'], unique=False)
    op.create_index(op.f('idx_file_asset_core_id'), 'file_asset', ['core_id'], unique=False)
    op.create_index(op.f('idx_external_ids_source'), 'external_ids', ['source'], unique=False)
    op.create_index(op.f('idx_external_ids_core_id'), 'external_ids', ['core_id'], unique=False)
    # ### end Alembic commands ###
